dist: trusty
language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install:
  - composer require satooshi/php-coveralls:~0.6@stable

before_script:
  - mkdir -p build/logs
  - composer install
  - composer update -o

script: phpunit --debug --bootstrap tests/bootstrap.php --configuration phpunit.xml tests --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
